### PR TITLE
cleaned up markup and updated indentation

### PR DESCRIPTION
**Pull request by skbhardwaj**
Updated:
- added markup refinements
- updated indentation to 2 spaces

### CODE REVIEW

**Comment by skbhardwaj** [comment]
Hi,
Please let me know if we also need a .editorconfig , to ensure basic formatting.
Thanks & regards,

**Review by chrisdavidmills — CHANGES_REQUESTED** [review]
Hi there.

We don't use XHTML-style self-closing slashes on MDN code, so you should remove those from the PR.

The rest of it looks helpful though, thanks.

Also, we don't tend to use editorconfig files on MDN code repos. It is a nice thought, but we have a lot of repos, so it'd be a lot of changes for not much gain, imo.

**Comment by skbhardwaj** [comment]
Hi,
Updated, thanks.

**Review by chrisdavidmills — APPROVED** [review]
Looks good, thanks @skbhardwaj !

**Pull request merged**
